# yaml-language-server: $schema=https://schema.log10x.com/pipelines/run/input/forwarder/logstash/report/schema.json

# 🔟❎ 'run' Logstash reporter configuration

# Configure an input that reads events from a Logstash forwarder.
# To learn more see https://doc.log10x.com/run/input/forwarder/logstash/report/

# This file operates used in conjunction with:
# https://github.com/log-10x/config/blob/main/pipelines/run/input/forwarder/logstash/report/tenx-pipe-out.conf

# tenx-pipe-out.conf configures a Logstash forwarder to launch a 10x 'run' subprocess to
# write events to its stdin pipe for aggregation and reporting.

# Set the 10x pipeline to 'run'
tenx: run

# =============================== Dependencies ================================

include: run/modules/input/forwarder/logstash/input
