# 10x Logstash pipe output configuration
#
# The snippet below is added to a Logstash configuration to
# launch and write events into an 10x sub-process to aggregate
# and report on data flowing through a Logstash pipeline to a target analytics backend.

output {
  # Send incoming events to the 10x executable via the 'pipe' output plugin.
  #
  pipe {
    id => "tenx_pipeline"

    # Don't close the 10x process due to events inactivity.
    ttl => -1

    # NIX
    command => "${TENX_BIN:/opt/tenx-edge/bin/tenx} run @run/input/forwarder/logstash/report/config.yaml @run/apps/edge/reporter"

    # WIN
    #command => "${TENX_BIN:'c:\program files\tenx\tenx-edge.exe'} run @run/input/forwarder/logstash/report/config.yaml @run/apps/edge/reporter"
  }
}
