# yaml-language-server: $schema=https://schema.log10x.com/pipelines/run/input/forwarder/fluentd/report/schema.json

# 🔟❎ 'run' Fluentd reporter configuration

# Configure an input that reads events from a Fluentd forwarder.
# To learn more see https://doc.log10x.com/run/input/forwarder/fluentd/report/

# This config runs in conjunction with the instructions provided in:
# https://doc.log10x.com/run/input/forwarder/fluentd/report/#install

# Set the 10x pipeline to 'run'
tenx: run

# =============================== Dependencies ================================

# read events from the forwarder using the Fluentd 'forward' protocol
# https://docs.fluentd.org/output/forward
include: run/modules/input/forwarder/fluentd/input
