# yaml-language-server: $schema=https://schema.log10x.com/pipelines/compile/scanners/logMethods/schema.json

# 🔟❎ 'compile' log methods configuration

# Set the 10x pipeline to 'compile'
tenx: compile

# ============================ Log Options =============================

log:

  # 'methods' lists known method names collected from common logging
  #  frameworks used to indicate source code logging events to stream at runtime.

  #  Identifying those points in source code that perform logging operations
  #  and marking them within an output symbol unit file (*.json)
  #  allows the 'run' pipeline to correlate each TenXObject structured from the event
  #  data back to its origin in the codebase.

  #  To learn more about symbol contexts and their use, see https://doc.log10x.com/run/transform/symbol/#contexts
  methods:

    # Assertions are not enabled by default as they are less likely to appear in prod logs
    # - Assert
    # - assert
    # - assertEquals
    # - assertEqual

    - exception

    - Log
    - LOG
    - log
    - BOOST_LOG_TRIVIAL

    - trace
    - Trace
    - log_trace
    - logTrace
    - TRACE
    - LOG_TRACE

    - debug
    - Debug
    - logDebug
    - log_debug
    - DEBUG
    - LOG_DEBUG
    - Debugf

    - info
    - Info
    - log_info
    - logInfo
    - INFO
    - LOG_INFO
    - information
    - LogInformation
    - InfoF

    - warn
    - Warn
    - log_warn
    - logWarn
    - WARN
    - LOG_WARN
    - WarnF

    - warning
    - logWarning
    - LOG_WARNING

    - error
    - Error
    - logError
    - log_error
    - ERROR
    - LOG_ERROR
    - ErrorF

    - err

    - fatal
    - Fatal
    - log_fatal
    - logFatal
    - FATAL
    - LOG_FATAL
    - FatalF

    - critical
    - Panic

  # 'methodRegex' specifies an optional regex that will be applied
  #  to a scanned source code method/function name. If matched, the method
  #  will be considered to be a 'logging method' (see above).
  #  For example: ^(log|Log)|(Log|log)$
  methodRegex: null

  # 'streams' defines which source code variables within
  #  this ANTLR syntax are treated as output streams (e.g. stdout, stderr, cerr).
  #  Literal constants (e.g. "error connecting to {}") passed to a variable
  #  listed below (e.g. 'cout') will be assigned a 'logger_method_invoke'
  #  symbol source context.
  streams:

  # - assert
    - cout
    - cerr
    - Error
    - Debug
    - err
    - out
    - Console
