# 10x Logstash pipe output configuration
#
# Add this Logstash configuration to 'pipelines.yml' to launch
# an 10x subprocess into which to write events to optimize.
#
# This file is used in conjunction with a Logstash input '.conf' file
# used to read optimized events from the 10x subprocess:
#   unix: run/config/forwarder/logstash/optimize/tenx-pipe-in-unix.conf
#   win:  run/config/forwarder/logstash/optimize/tenx-pipe-in-tcp.conf


input {
  # Getting data into this Logstash pipeline.
  # When using the pipelines.yml approach, this sets Logstash's internal address
  # for data input into this pipeline.
  #
  # Alternatively, any other Logstash input plugin may be used when incorporating
  # 10x into your Logstash config
  #
  pipeline {
    address => tenx_input_pipeline
  }
}

output {
  # Send incoming events to the 10x executable via the 'pipe' output plugin.
  #
  pipe {
    id => "tenx_pipeline"

    # Don't close the 10x process due to events inactivity.
    ttl => -1

    # NIX
    command => "${TENX_BIN:/opt/tenx-edge/bin/tenx} run @run/input/forwarder/logstash/optimize/config.yaml @run/apps/edge/optimizer"

    # WIN
    #command => "${TENX_BIN:'c:\program files\tenx\tenx.exe'} run @run/input/forwarder/logstash/optimize/config.yaml @run/apps/edge/optimizer"
  }
}
