# 10x Logstash Unix domain socket input configuration
#
# Add this Logstash configuration to 'pipelines.yml' to launch
# a 10x subprocess from which to read events via a Unix domain socket.
#
# Add this file as a pipeline for your Logstash pipelines.yml config to incorporate
# it into your configuration.
#
# This file is used in conjunction with:
# run/config/forwarder/logstash/optimize/tenx-pipe-out.conf
#

# Read back data from 10x via a Unix domain socket.
# The 10x 'run' pipeline captures the socket address using 'tenx_marker_pipeline_unix_address' in '/run/modules/input/forwarder/logstash/output/unix/stream.yaml'
#
input {
  unix {
    id => "tenx_unix_input"
    path => "${tenx_marker_pipeline_unix_address:/tmp/tenx_logstash.sock}"
    force_unlink => true
    tags => ["tenx"]
    codec => json_lines
  }
}

# Process incoming events; templates get sent to Elastic, and everything else gets
# processed by the rest of the Logstash pipeline.
#
output {
  if [template] and [templateHash] {
    # Send 10x templates generated to your ElasticSearch cluster to allow
    # elasticsearch to run queries on 10x encoded indices.
    #
    elasticsearch {
      # Fill in your ElasticSearch cluster connection details here.
      #
      # For more info see:
      # https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-options
      #
      hosts => "localhost"

      # Explicitly set the id key inside elastic to the value of templateHash
      # This is important as the l1es plugin depends on being able to find explicitly
      # templates based on their hash.
      #
      document_id => "%{[templateHash]}"

      # Index to store 10x templates.
      # It needs to match the configuration of the l1es plugin and should most likely not be changed.
      #
      index => l1es_dml
    }
  } else {
    # Send all other data received from the 10x executable to the next logstash
    # pipeline for further processing, depending on your configuration.
    #
    # Alternatively, any other Logstash output plugin may be used when directly incorporating
    # 10x into your Logstash config
    #
    pipeline {
      send_to => user_output_pipeline
    }
  }
}
