# 10x Logstash Unix domain socket input configuration
#
# Add this Logstash pipeline configuration file to 'pipelines.yml' to 
# read events from a 10x subprocess via a Unix domain socket.
#
# This file is used in conjunction with:
# run/config/forwarder/logstash/regulate/tenx-pipe-out.conf
#

# Read back data from 10x via a Unix domain socket.
# The 10x 'run' pipeline captures the socket address using 'tenx_marker_pipeline_unix_address' in '/run/modules/input/forwarder/logstash/output/unix/stream.yaml'
input {
  unix {
    id => "tenx_unix_input"
    path => "${tenx_marker_pipeline_unix_address:/tmp/tenx_logstash.sock}"
    force_unlink => true
    tags => ["tenx"]
    codec => json_lines
  }
}

# Process incoming events; templates get sent to Elastic, and everything else gets
# processed by the rest of the Logstash pipeline.
#
output {
   pipeline {
    send_to => user_output_pipeline
  }
}
