#
# 🔟❎  Compiler app main config

# The compile app produces symbol library files which enable 10x apps to
# transform log/trace events into well-defined TenXObjects at runtime.

# To learn more see https://doc.log10x.com/apps/compiler

# =========================== Bootstrap Compiler ==============================

# To learn more see https://doc.log10x.com/compile/bootstrap

tenx: compile

runtimeName: $=TenXEnv.get("TENX_RUNTIME_NAME", "myCompiler")

# ============================ Load App Modules ===============================

# Uncomment and edit selected config.yaml files in the folders below (e.g., compile/scanners/config.yaml)

include:

# ------------------------------ App settings ---------------------------------

  # Load general app settings:
  - compiler

  # Load gitops settings for pulling additional assets from Github.
  # Edit the gitops/config.yaml file with specific config
  #
  # For additional info see - https://doc.log10x.com/config/github
  - gitops

  # --------------------------- Process Inputs --------------------------------

  # Process input source code and binary files on disk.

  - compile/scanners  # https://doc.log10x.com/compile/scan

  # ---------------------------- Pull Inputs ----------------------------------

  # This application can fetch source/binary files from remote inputs
  # Uncomment and edit config files (e.g. compile/pull/github/config.yaml) to remote pull
  #
  - compile/pull/github       # https://doc.log10x.com/compile/pull/github
  - compile/pull/docker       # https://doc.log10x.com/compile/pull/docker
  - compile/pull/helm         # https://doc.log10x.com/compile/pull/helm
  # - compile/pull/artifactory  # https://doc.log10x.com/compile/pull/artifactory

  # ---------------------------- Link Output ----------------------------------

  # Link output files into a single symbol library artifact for runtime use

  - compile/link              # https://doc.log10x.com/compile/link

  # ---------------------------- Push Output ----------------------------------

  # Push output files to GitHub for use by subsequent compile and run instances

  # - compile/push            # https://doc.log10x.com/compile/push
