# yaml-language-server: $schema=https://schema.log10x.com/pipelines/run/input/forwarder/filebeat/report/schema.json

# 🔟❎ 'run' Filebeat reporter configuration

# Configure an input that reads events from a Filebeat forwarder.
# To learn more see https://doc.log10x.com/run/input/forwarder/filebeat/report/

# Set the 10x pipeline to 'run' 
tenx: run

# =============================== Dependencies ================================

include:

  # Input module to read events from Filebeat into 10x pipeline
  - run/modules/input/forwarder/filebeat/input
