# yaml-language-server: $schema=schema.json

#
# 🔟❎ GitOps configuration

# This config file pulls symbol, config and lookup files from a remote repo to
# enable centralized configuration management via GitHub.

# To learn more see https://doc.log10x.com/config/github

# The target 10x pipeline to run (e.g., run, compile) is specified in the config files pulled from the repo
tenx: any

include:

  - source: github

    options:
      # 'enabled' controls whether to enable this pull config
      enabled: false # (REQUIRED)

      # 'token' specifies an access token for accessing the Github repo.
      #  To learn more see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
      token: $=TenXEnv.get("GH_TOKEN")

      # 'repo' specifies the GitHub user/repo from which to pull
      repo: null # (REQUIRED)

      # 'branch' on 'repo' (if null, uses default repo default branch)
      branch: main

       # 'paths' specifies Glob patterns within 'repo' to pull and extract to a temp folder.
      paths:
        - test
        # - config/*.yaml      # https://doc.log10x.com/config/yaml
        # - symbols/*.10x.tar  # https://doc.log10x.com/run/symbol
        # - lookups/*.csv      # https://doc.log10x.com/api/js/#TenXLookup
        # - scripts/*.js       # https://doc.log10x.com/api/js

      # 'syncInterval' specifies an interval by which check to check the remote branch for updates (null to disable)
      #  This interval works in conjunction with: https://doc.log10x.com/run/reload
      syncInterval: 5min
