#
# 🔟❎ Object storage query app config

# Launch object storage queries. To learn more see https://doc.log10x.com/apps/cloud/analyzer/#query

# ============================ Bootstrap Runtime ==============================

# Initialize the runtime. To learn more see https://doc.log10x.com/run/bootstrap

tenx: run

runtimeName: $=TenXEnv.get("TENX_RUNTIME_NAME", "myObjectStorageQuery")

# ============================ Load App Modules ===============================

include:

# Uncomment includes and edit their config.yaml files 

# ------------------------------ App settings ---------------------------------

  # Load app settings:
  - cloud/streamer/query

  # Load gitops settings for pulling additional assets from Github.
  # Edit the gitops/config.yaml file with specific config
  #
  # For additional info see - https://doc.log10x.com/config/github
  - gitops

# ----------------------------- Launch Queries --------------------------------

  # Execute the stream queries configured in:
  - run/input/objectStorage/query
