# yaml-language-server: $schema=https://schema.log10x.com/pipelines/compile/scanners/advanced/schema.json

# 🔟❎ 'compile' symbol scanner advanced config

# Configure input and output options for the compile pipeline.
# To learn more see https://doc.log10x.com/compile/scan/

# Set the 10x pipeline to 'compile'
tenx: compile

inputPaths: []

# ============================ Advanced options ===============================

# ----------------------------- Tokenizer options -----------------------------

# Tokenization options provide control over how the symbol scanners parse source and config file input.
# To learn more https://doc.log10x.com/compile/scan/#tokenize

# 'tokenDelims' defines which characters break a string of event characters into tokens to 
#  classify as symbols or variables.
tokenDelims: "<>|. ][:-+/*=\\,{}_();'\"$\t\n@"

# 'fileExtStringFormats' controls which characters identify the start of a format specifier (https://en.wikipedia.org/wiki/Printf#Format_specifier). 
fileExtStringFormats: 
  - .java:%
  - .py:{
  - .js:${
  - .php:$
  - .swift:\(
  - .kt:$
  - .rb:#{
  - .ex:#{
  - .c:%
  - .cpp:%
  - .cs:{
  - .go:%
  - .rs:{
  - .ts:${
  - .pl:$
  - .sh:$
  - .r:%
  - .m:%
  - .scala:$


maxSymbol:

# 'unitsPerToken' controls the maximum number of symbol units to load from the 
#  pipeline's symbol library when searching for the origin of a specific TenXTemplate symbol. 
  unitsPerToken: 128

# ----------------------------- Subprocess options ----------------------------

# Subprocess options control whether scanners execute in the current 10x Engine instance
# or via a sub-process to provide better isolation over parsing of complex source code ASTs. 

# To learn more https://doc.log10x.com/compile/scan/#subprocess_1

# 'unitsToScanPerBatch' sets the maximum number of input files to scan per subprocess instance.
#  When this threshold is exceeded the current subprocess terminated and a new one is spawned until scan is complete.
unitsToScanPerBatch: 200

scan:

# ----------------------------- Threading  options ----------------------------

  # 'threadPoolSize'controls the maximum number of threads to concurrently
  #  process input source/binary files. If the value is between 0 and 1, the number calculates 
  #  a percentage of available cores (e.g., 0.5 = use up to 50% of available cores).
  #  If the value is >= 1, the value sets a fixed number of threads (e.g., 10 = 10 threads).
  #  If the value is 1, allocate a single thread to process input files.

  # To learn more see https://doc.log10x.com/compile/scan/#parallel

  threadPoolSize: "0.5"

  # 'scanUnitTimeout' sets the timeout interval when scanning a source/binary input
  #  file before dropping it. 
  unitTimeout: 30s

  # 'scanOperationTimeout' sets the timeout interval for the entire scanning operation
  #  before terminating it.
  operationTimeout: 10m

# -------------------------------- Debug Option -------------------------------

# The settings below provide control over what information is logged
# to console/file when scanning input source code/text/binary files for symbol values.

# These options are primarily used when adding support for a new programming language
# syntax via the 'ANTLR' scanner, text file formats via the Jackson 'text' scanner
# or an external command using the 'executable' scanner.

  debug:

  # 'origins' lists names of input source/binary files 
  #  (e.g. .class, .js, .yaml, .exe) for which debug information
  #  is printed to the console via 'consoleOut' log4j logger.

  #  Printed output is dependent on the scanner assigned to process the input file  
  #  and usually includes the AST of the input file from which tokens are selected.

  #  This information can be used when debugging which symbols are extracted
  #  from an input file in the context of an 'antlr', 'text' or 'executable' scanner. 
  #  Set to '*' to match all input files. 
    origins: [
  #   '*'
    ]

  # 'symbols' lists the values of nodes within the AST of a
  #  target input file (e.g. MyClass, MyEnum, myFunc, ..) for which 
  #  debug information is printed to the console via the 'consoleOut' logger.
  #  This includes source context (e.g. class, enum) and path within the AST 
  #  in which the node was detected. Set to '*' to match all AST nodes. 
    symbols: [
     #'*'
    ]

  # 'inProcess' controls whether to scan source/binary input files from within the current
  #  10x process or launch a sequential series subprocesses for better isolation
  # inProcess: true  

  # 'force' enables scanning of source/binary input files even if a matching
  #  symbol unit was found in 'inputPaths'. This flag is useful when debugging
  #  an Antlr/text/exec scanner using 'debugOrigins' and 'debugSymbols'
  #  to ensure a scan takes place even if a matching symbol unit is found.
  
  # force: false 

